version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    restart: unless-stopped