global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ngx-alerts@example.com'
  smtp_auth_username: 'your-email@example.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

# Inhibition rules to suppress certain alerts
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job', 'instance']

# Alert routing configuration
route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
  # Critical alerts - immediate notification
  - match:
      severity: critical
    receiver: critical-alerts
    continue: true
    
  # Warning alerts - batched notifications
  - match:
      severity: warning
    receiver: warning-alerts
    group_wait: 5m
    group_interval: 10m
    repeat_interval: 4h
    
  # Business metrics - daily summary
  - match:
      component: business
    receiver: business-alerts
    group_wait: 30m
    group_interval: 1h
    repeat_interval: 24h

# Notification receivers
receivers:
- name: 'default'
  email_configs:
  - to: 'ops-team@example.com'
    headers:
      Subject: 'NGX Voice Agent Alert: {{ .GroupLabels.alertname }}'
    html: |
      <h2>NGX Voice Sales Agent Alert</h2>
      <h3>{{ .GroupLabels.alertname }}</h3>
      
      <h4>Alerts:</h4>
      {{ range .Alerts }}
      <p>
        <b>Status:</b> {{ .Status }}<br>
        <b>Summary:</b> {{ .Annotations.summary }}<br>
        <b>Description:</b> {{ .Annotations.description }}<br>
        <b>Component:</b> {{ .Labels.component }}<br>
        <b>Time:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      </p>
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'critical-alerts@example.com'
    headers:
      Subject: '[CRITICAL] NGX Voice Agent: {{ .GroupLabels.alertname }}'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#ngx-critical-alerts'
    title: 'CRITICAL: {{ .GroupLabels.alertname }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    color: 'danger'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'warnings@example.com'
    headers:
      Subject: '[WARNING] NGX Voice Agent: {{ .GroupLabels.alertname }}'
  
- name: 'business-alerts'
  email_configs:
  - to: 'business-metrics@example.com'
    headers:
      Subject: 'NGX Business Metrics Report'
    html: |
      <h2>NGX Voice Sales Agent - Business Metrics</h2>
      {{ range .Alerts }}
      <p>
        <b>Metric:</b> {{ .GroupLabels.alertname }}<br>
        <b>Description:</b> {{ .Annotations.description }}<br>
        <b>Time:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      </p>
      {{ end }}

# Templates for alert formatting
templates:
- '/etc/alertmanager/templates/*.tmpl'